apiVersion: v1
kind: Service
metadata:
  labels:
    name: user-service
  name: user-service
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8001
      targetPort: 8001
  selector:
    app: user-service
