apiVersion: v1
kind: Service
metadata:
  labels:
    name: zookeeper
  name: zookeeper
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  ports:
    - protocol: "TCP"
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
