---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: chat-service
  name: chat-service
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8006
      targetPort: 8006
  selector:
    app: chat-service
