---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lists-service
  namespace: twitter-website
spec:
  selector:
    matchLabels:
      app: lists-service
  template:
    metadata:
      labels:
        app: lists-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: lists-service
        image: neoop1/twitter-lists-service:latest
        ports:
        - containerPort: 8005
        env:
        - name: EUREKA_HOST
          value: "eureka-server"
        - name: CONFIG_SERVER_HOST
          value: "config-server"
        - name: DATASOURCE_HOST
          value: "postgres"
        - name: ZIPKIN_HOST
          value: "zipkin"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        readinessProbe:
              httpGet:
                path: /actuator/health
                port: 8005
              initialDelaySeconds: 120
              periodSeconds: 15
              failureThreshold: 5
              timeoutSeconds: 5
        livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8005
              initialDelaySeconds: 40
              periodSeconds: 15
              failureThreshold: 5
              timeoutSeconds: 5
        resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

