---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: twitter-website
  annotations:
        prometheus.io/scrape: 'true'
spec:
  selector:
    app: minio
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  type: ClusterIP