---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-volume-claim
  labels:
    app: grafana
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi


