---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests: 
            memory: "1Gi"
            cpu: "500m"
        env:
          - name: GF_SECURITY_ADMIN_USER
            value: admin
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: admin
            
          - name: GF_PATHS_DATA
            value: /var/lib/grafana/
          - name: GF_PATHS_HOME
            value: /usr/share/grafana
          - name: GF_PATHS_PROVISIONING
            value: /etc/grafana/provisioning/
          - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
            value: /etc/grafana/provisioning/dashboards/micrometer-spring-dashboard.json
 
        volumeMounts:

          - name: grafana-volume
            mountPath: /var/lib/grafana

          - name: grafana-datasources
            mountPath:  /etc/grafana/provisioning/datasources/prometheus.yaml
            subPath: prometheus.yaml

          - name: twitter-website-resources-dashboard
            mountPath: 	/etc/grafana/provisioning/dashboards/twitter-website-resources-dashboard
            subPath: twitter-website-resources-dashboard.json

          - name: prometheus-node-exporter-dashboard
            mountPath: 	/etc/grafana/provisioning/dashboards/prometheus-node-exporter-dashboard.json
            subPath: prometheus-node-exporter-dashboard.json

          - name: micrometer-spring-dashboard
            mountPath: 	/etc/grafana/provisioning/dashboards/micrometer-spring-dashboard.json
            subPath: micrometer-spring-dashboard.json

      restartPolicy: Always
      terminationGracePeriodSeconds: 60

      volumes:
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: grafana-volume-claim

        - name: grafana-datasources
          configMap:
            name: prometheus-datasource

        - name: twitter-website-resources-dashboard
          configMap:
            name: twitter-website-resources-dashboard

        - name: prometheus-node-exporter-dashboard
          configMap:
            name: prometheus-node-exporter-dashboard

        - name: micrometer-spring-dashboard
          configMap:
            name: micrometer-spring-dashboard

