apiVersion: v1
kind: Service
metadata:
  labels:
    name: websocket-service
  name: websocket-service
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8022
      targetPort: 8022
  selector:
    app: websocket-service
