---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: lists-service
  name: lists-service
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8005
      targetPort: 8005
  selector:
    app: lists-service


