apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: twitter-website
spec:
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: email-service
        image: neoop1/twitter-email-service:latest
        ports:
        - containerPort: 8020
        env:
        - name: EUREKA_HOST
          value: "eureka-server"
        - name: CONFIG_SERVER_HOST
          value: "config-server"
        - name: ZIPKIN_HOST
          value: "zipkin"          
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8020
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 5
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8020
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 5
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi