apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: twitter-website
  annotations:
        prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  selector:
    app: api-gateway
