---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: notification-service
  name: notification-service
  namespace: twitter-website
  annotations:
        prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8007
      targetPort: 8007
  selector:
    app: notification-service


