---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tag-service
  name: tag-service
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8004
      targetPort: 8004
  selector:
    app: tag-service
