apiVersion: v1
kind: Service
metadata:
  labels:
    name: topic-service
  name: topic-service
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8003
      targetPort: 8003
  selector:
    app: topic-service
