---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: twitter-website
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: notification-service
        image: neoop1/twitter-notification-service:latest
        ports:
        - containerPort: 8007
        env:
        - name: EUREKA_HOST
          value: "eureka-server"
        - name: CONFIG_SERVER_HOST
          value: "config-server"
        - name: DATASOURCE_HOST
          value: "postgres"
        - name: ZIPKIN_HOST
          value: "zipkin"
        - name: RABBITMQ_HOST
          value: "rabbitmq"       
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8007
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 5
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8007
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 5
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
