---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: broker
  name: broker
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 9092
      targetPort: 9092
  selector:
    app: broker
