{
 "title": "Docker Java Micrometer",
 "description": "Java metrics exposed with Micrometer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Microservice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "postgres",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_last_seen{name=\"postgres\"} OR on() vector(0)",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "zookeeper",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_last_seen{name=\"zookeeper\"} OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "zipkin",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_last_seen{name=\"zipkin\"} OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "frontend",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_last_seen{name=\"frontend\"} OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "broker",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_last_seen{name=\"broker\"} OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "eureka-server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"eureka-server\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Load",
   "type": "timeseries",
   "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "system_load_average_1m" }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "api-gateway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"api-gateway\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "notification-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"notification-service\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "image-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"image-service\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "topic-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"topic-service\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tweet-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"tweet-service\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "chat-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"chat-service\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "lists-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"lists-service\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "websocket-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"websocket-service\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tag-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"tag-service\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "config-server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"config-server\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "user-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"user-service\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "email-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"email-service\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Threads Peak",
   "type": "timeseries",
   "description": "The peak live thread count since the Java virtual machine started or peak was reset",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_peak_threads" }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}} / {{area}} ({{job}})" }
   ]
  },
  {
   "title": "JVM GC Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_gc_live_data_size_bytes", "legendFormat": "live ({{job}})" },
    { "expr": "jvm_gc_max_data_size_bytes", "legendFormat": "max ({{job}})" }
   ]
  },
  {
   "title": "Live Daemon Threads",
   "type": "timeseries",
   "description": "The current number of live daemon threads",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_daemon_threads" }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "description": "The uptime of the Java virtual machine",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "stat",
   "description": "The starttime of the Java virtual machine",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds * 1000"
    }
   ]
  },
  {
   "title": "Error Events",
   "type": "stat",
   "description": "Number of error level events that made it to the logs",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"error\"}"
    }
   ]
  },
  {
   "title": "Logback Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Processor Count",
     "type": "stat",
     "description": "The number of processors available to the Java virtual machine",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "system_cpu_count" }
     ]
    },
    {
     "title": "Trace Events",
     "type": "stat",
     "description": "Number of trace level events that made it to the logs",
     "gridPos": { "h": 10, "w": 7, "x": 11, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "logback_events_total{level=\"trace\"}"
      }
     ]
    },
    {
     "title": "Debug Events",
     "type": "stat",
     "description": "Number of debug level events that made it to the logs",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "logback_events_total{level=\"debug\"}"
      }
     ]
    },
    {
     "title": "Warn Events",
     "type": "stat",
     "description": "Number of warn level events that made it to the logs",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "logback_events_total{level=\"warn\"}"
      }
     ]
    },
    {
     "title": "Info Events",
     "type": "stat",
     "description": "Number of info level events that made it to the logs",
     "gridPos": { "h": 22, "w": 13, "x": 10, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "logback_events_total{level=\"info\"}"
      }
     ]
    },
    {
     "title": "Live Total Threads",
     "type": "timeseries",
     "description": "The current number of live threads including both daemon and non-daemon threads",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "jvm_threads_live_threads" }
     ]
    },
    {
     "title": "Buffer Mem Used",
     "type": "timeseries",
     "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "GC Promoted Total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 13, "x": 10, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_gc_memory_promoted_bytes_total",
       "legendFormat": " {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Buffer Count",
     "type": "timeseries",
     "description": "An estimate of the number of buffers in the pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "jvm_buffer_count_buffers", "legendFormat": "{{id}}" }
     ]
    },
    {
     "title": "Used Memory",
     "type": "timeseries",
     "description": "The amount of used memory",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}} ({{area}})" }
     ]
    },
    {
     "title": "Buffer Capacity",
     "type": "timeseries",
     "description": "An estimate of the total capacity of the buffers in this pool",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_total_capacity_bytes",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "timeseries",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "jvm_memory_max_bytes", "legendFormat": "{{id}} ({{area}})" }
     ]
    },
    {
     "title": "Committed Memory",
     "type": "timeseries",
     "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "jvm_memory_committed_bytes", "legendFormat": "{{id}} ({{area}})" }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Max Data Size",
     "type": "timeseries",
     "description": "Max size of old generation memory pool",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "jvm_gc_max_data_size_bytes", "legendFormat": "{{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Live Data Size",
     "type": "timeseries",
     "description": "Size of old generation memory pool after a full GC",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "jvm_gc_live_data_size_bytes", "legendFormat": "{{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Pause Count",
     "type": "timeseries",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "jvm_gc_pause_seconds_count" }
     ]
    },
    {
     "title": "Allocation Rate",
     "type": "timeseries",
     "description": "Incremented for an increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_gc_memory_allocated_bytes_total"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Requests Count",
     "type": "timeseries",
     "description": "Count of servlet requests",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count",
       "legendFormat": "{{method}} {{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "HTTP Requests Time",
     "type": "timeseries",
     "description": "Timer of servlet requests",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_sum",
       "legendFormat": "{{method}} {{uri}} - {{status}}"
      }
     ]
    }
   ]
  }
 ]
}