server:
    port: 8761

spring:
    application:
        name: eureka-server
    zipkin:
        base-url: http://${ZIPKIN_HOST:localhost}:9411

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
        fetchRegistry: ${FETCH_REGISTRY:false}
        registerWithEureka: ${REGISTER_WITH_EUREKA:false}
    instance:
        hostname: ${HOST_NAME:${spring.application.name}}  # work on swarm
        instance-id: ${spring.application.name}:${random.uuid}
        leaseRenewalIntervalInSeconds: ${LEASE_RENEWAL_INTERVAl_IN_SECONDS:10}
        leaseExpirationDurationInSeconds: ${LEASE_EXPIRATION_DURATIONIN_SECONDS:20}
        preferIpAddress: ${PREFER_IP_ADDRESS:false}



management:
  endpoints:
    health:
     show-details: always
    web:
      base-path: /actuator
      exposure:
        include: health

