apiVersion: v1
kind: Service
metadata:
  labels:
    name: eureka-server
  name: eureka-server
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8761
      targetPort: 8761
  selector:
    app: eureka-server
