---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres
  name: postgres
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: NodePort
