apiVersion: v1
kind: Service
metadata:
  labels:
    name: tweet-service
  name: tweet-service
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8002
      targetPort: 8002
  selector:
    app: tweet-service
