server:
    port: 8020

spring:
    application:
        name: email-service
    zipkin:
        base-url: http://${ZIPKIN_HOST:localhost}:9411
    mail:
        host: smtp.gmail.com
        username: twitter.spring.reactjs@gmail.com
        password: tqzkgmxlwyukvwpt
        port: 465
        protocol: smtps
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    kafka:
        bootstrap-servers: ${BROKER_HOST:localhost}:9092
        consumer:
            group-id: email
mail:
    debug: false

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
        fetchRegistry: ${FETCH_REGISTRY:true}
        registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    instance:
        hostname: ${HOST_NAME:${spring.application.name}}  # work on swarm
        instance-id: ${spring.application.name}:${random.uuid}
        leaseRenewalIntervalInSeconds: ${LEASE_RENEWAL_INTERVAl_IN_SECONDS:10}
        leaseExpirationDurationInSeconds: ${LEASE_EXPIRATION_DURATIONIN_SECONDS:20}
        preferIpAddress: ${PREFER_IP_ADDRESS:false}

management:
    endpoints:
        web:
            exposure:
                include: 'prometheus, health'
    metrics:
        export:
            prometheus:
                enabled: true
        distribution:
            percentiles-histogram:
                "[http.server.requests]": true
