server:
    port: 8021

spring:
    application:
        name: image-service
    zipkin:
        base-url: http://${ZIPKIN_HOST:zipkin}:9411


amazon:
    s3:
        bucket:
            name: twitterclonestorage
    #aws:
    #    access-key: AKIATP4TDBGPAJUNI5EY
    #    secret-key: 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
    aws:
        access-key: "minio-user"
        secret-key: "minio-password"
        endpoint: http://minio-service.twitter-website.svc.cluster.local:9000 ##minio server 

    



eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:eureka-server}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: ${EUREKA_HOST:localhost}
        preferIpAddress : true

management:
    endpoints:
        web:
            exposure:
                include: 'prometheus, health'
    metrics:
        export:
            prometheus:
                enabled: true
        distribution:
            percentiles-histogram:
                "[http.server.requests]": true
