server:
    port: 8005
spring:
    application:
        name: lists-service
    datasource:
        url: jdbc:postgresql://localhost:5432/lists-test
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
            data-locations: classpath:sql-test/clear-lists-db.sql, classpath:sql-test/populate-lists-db.sql
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
        fetchRegistry: ${FETCH_REGISTRY:true}
        registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    instance:
        hostname: ${HOST_NAME:${spring.application.name}}  # work on swarm
        instance-id: ${spring.application.name}:${random.uuid}
        leaseRenewalIntervalInSeconds: ${LEASE_RENEWAL_INTERVAl_IN_SECONDS:10}
        leaseExpirationDurationInSeconds: ${LEASE_EXPIRATION_DURATIONIN_SECONDS:20}
        preferIpAddress: ${PREFER_IP_ADDRESS:false}
