server:
    port: 8007
spring:
    application:
        name: notification-service
    datasource:
        url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/notification-test
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
            data-locations: classpath:sql-test/clear-notification-db.sql, classpath:sql-test/populate-notification-db.sql
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: notification-test
eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: ${EUREKA_HOST:eureka-server}
        #preferIpAddress : true

