server:
    port: 8002
spring:
    application:
        name: tweet-service
    datasource: 
        url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/tweet
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            generate-ddl: true  
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        locations: classpath:db/migration
    zipkin:
        base-url: http://${ZIPKIN_HOST:localhost}:9411
    kafka:
        bootstrap-servers: ${BROKER_HOST:localhost}:9092
        consumer:
            group-id: tweet
    jackson: # No serializer found for class java.io.FileDescriptor and no properties discovered to create BeanSerializer | to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS
        serialization:
            FAIL_ON_EMPTY_BEANS: false
resilience4j:
    circuitbreaker:
        instances:
            image-service:
                minimum-number-of-calls: 5
            lists-service:
                minimum-number-of-calls: 5
            websocket-service:
                minimum-number-of-calls: 5
feign:
    circuitbreaker:
        enabled: true

google:
    api:
        url: https://www.googleapis.com/youtube/v3/videos?id=%s&key=%s&part=snippet,contentDetails,statistics,status
        key: AIzaSyBtQYzGSmcCzqOztibg1BgSTqv0xwg1D-M

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
        fetchRegistry: ${FETCH_REGISTRY:true}
        registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    instance:
        hostname: ${HOST_NAME:${spring.application.name}}  # work on swarm
        instance-id: ${spring.application.name}:${random.uuid}
        leaseRenewalIntervalInSeconds: ${LEASE_RENEWAL_INTERVAl_IN_SECONDS:10}
        leaseExpirationDurationInSeconds: ${LEASE_EXPIRATION_DURATIONIN_SECONDS:20}
        preferIpAddress: ${PREFER_IP_ADDRESS:false}

management:
    endpoints:
        web:
            exposure:
                include: 'prometheus, health'
    metrics:
        export:
            prometheus:
                enabled: true
        distribution:
            percentiles-histogram:
                "[http.server.requests]": true
