server:
    port: 8001
spring:
    application:
        name: user-service
    datasource:
        url: jdbc:postgresql://${DATASOURCE_HOST:postgres}:5432/user
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            generate-ddl: true       
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        locations: classpath:db/migration
    zipkin:
        base-url: http://${ZIPKIN_HOST:zipkin}:9411
    kafka:
        bootstrap-servers: broker:9092
        consumer:
            group-id: user

resilience4j:
    circuitbreaker:
        instances:
            tweet-service:
                minimum-number-of-calls: 5
feign:
    circuitbreaker:
        enabled: true

eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:eureka-server}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: ${EUREKA_HOST:localhost}
        preferIpAddress : true


management:
    endpoints:
        web:
            exposure:
                include: 'prometheus, health'
    metrics:
        export:
            prometheus:
                enabled: true
        distribution:
            percentiles-histogram:
                "[http.server.requests]": true
