{
 "title": "Java Micrometer",
 "description": "Java metrics exposed with Micrometer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "api-gateway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"api-gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "broker",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"broker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "image-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"image-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "config-server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"config-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "email-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"email-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eureka-server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"eureka-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Load",
   "type": "timeseries",
   "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "system_load_average_1m" }
   ]
  },
  {
   "title": "lists-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"lists-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "notification-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"notification-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tag-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"tag-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "topic-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"topic-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tweet-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"tweet-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "user-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_endpoint_address_available{endpoint=\"user-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "zookeeper",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"zookeeper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "websocket-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"websocket-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "chat-service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{endpoint=\"chat-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "frontend",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "postgres",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "zipkin",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{endpoint=\"zipkin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}} / {{area}} ({{job}})" }
   ]
  },
  {
   "title": "JVM Threads Peak",
   "type": "timeseries",
   "description": "The peak live thread count since the Java virtual machine started or peak was reset",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_peak_threads" }
   ]
  },
  {
   "title": "JVM GC Data",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_gc_live_data_size_bytes", "legendFormat": "live ({{job}})" },
    { "expr": "jvm_gc_max_data_size_bytes", "legendFormat": "max ({{job}})" }
   ]
  },
  {
   "title": "GC Promoted Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total",
     "legendFormat": " {{job}}"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "stat",
   "description": "The starttime of the Java virtual machine",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds * 1000"
    }
   ]
  },
  {
   "title": "Processor Count",
   "type": "stat",
   "description": "The number of processors available to the Java virtual machine",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "description": "The uptime of the Java virtual machine",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Logback Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Warn Events",
   "type": "stat",
   "description": "Number of warn level events that made it to the logs",
   "gridPos": { "h": 20, "w": 9, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"warn\"}"
    }
   ]
  },
  {
   "title": "Error Events",
   "type": "stat",
   "description": "Number of error level events that made it to the logs",
   "gridPos": { "h": 20, "w": 9, "x": 9, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"error\"}"
    }
   ]
  },
  {
   "title": "Trace Events",
   "type": "stat",
   "description": "Number of trace level events that made it to the logs",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"trace\"}"
    }
   ]
  },
  {
   "title": "Info Events",
   "type": "stat",
   "description": "Number of info level events that made it to the logs",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"info\"}"
    }
   ]
  },
  {
   "title": "Live Daemon Threads",
   "type": "timeseries",
   "description": "The current number of live daemon threads",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_daemon_threads" }
   ]
  },
  {
   "title": "Live Total Threads",
   "type": "timeseries",
   "description": "The current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  {
   "title": "Debug Events",
   "type": "stat",
   "description": "Number of debug level events that made it to the logs",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"debug\"}"
    }
   ]
  },
  {
   "title": "Buffer Mem Used",
   "type": "timeseries",
   "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
   "gridPos": { "h": 10, "w": 10, "x": 8, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "JVM Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Buffer Count",
   "type": "timeseries",
   "description": "An estimate of the number of buffers in the pool",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_buffer_count_buffers", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "description": "The amount of used memory",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}} ({{area}})" }
   ]
  },
  {
   "title": "Buffer Capacity",
   "type": "timeseries",
   "description": "An estimate of the total capacity of the buffers in this pool",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_total_capacity_bytes",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "timeseries",
   "description": "The maximum amount of memory in bytes that can be used for memory management",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_memory_max_bytes", "legendFormat": "{{id}} ({{area}})" }
   ]
  },
  {
   "title": "Committed Memory",
   "type": "timeseries",
   "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_memory_committed_bytes", "legendFormat": "{{id}} ({{area}})" }
   ]
  },
  {
   "title": "JVM Garbage Collection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Data Size",
   "type": "timeseries",
   "description": "Max size of old generation memory pool",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_gc_max_data_size_bytes", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Live Data Size",
   "type": "timeseries",
   "description": "Size of old generation memory pool after a full GC",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_gc_live_data_size_bytes", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Pause Count",
   "type": "timeseries",
   "description": "Time spent in GC pause",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "jvm_gc_pause_seconds_count" }
   ]
  },
  {
   "title": "Allocation Rate",
   "type": "timeseries",
   "description": "Incremented for an increase in the size of the young generation memory pool after one GC to before the next",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total"
    }
   ]
  },
  {
   "title": "HTTP Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Requests Count",
   "type": "timeseries",
   "description": "Count of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Time",
   "type": "timeseries",
   "description": "Timer of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  }
 ]
}