apiVersion: v1
kind: Service
metadata:
  labels:
    name: config-server
  name: config-server
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 8888
  selector:
    app: config-server
