---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: twitter-website
spec:
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      serviceAccountName: default
      containers:
        - name: chat-service
          image: neoop1/twitter-chat-service:latest
          ports:
          - containerPort: 8006
          env:
          - name: EUREKA_HOST
            value: "eureka-server"
          - name: CONFIG_SERVER_HOST
            value: "config-server"
          - name: DATASOURCE_HOST
            value: "postgres"
          - name: ZIPKIN_HOST
            value: "zipkin"
          - name: rabbitmq
          readinessProbe:
              httpGet:
                path: /actuator/health
                port: 8006
              initialDelaySeconds: 120
              periodSeconds: 15
              failureThreshold: 5
              timeoutSeconds: 5
          livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8006
              initialDelaySeconds: 120
              periodSeconds: 15
              failureThreshold: 5
              timeoutSeconds: 5
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
