apiVersion: v1
kind: Service
metadata:
  labels:
    name: image-service
  name: image-service
  annotations:
        prometheus.io/scrape: 'true'
  namespace: twitter-website
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8021
      targetPort: 8021
  selector:
    app: image-service
