---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: twitter-website
spec:
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: image-service
        image: neoop1/twitter-image-service:latest
        ports:
        - containerPort: 8021
        env:
        - name: EUREKA_HOST
          value: "eureka-server"
        - name: CONFIG_SERVER_HOST
          value: "config-server"
        - name: ZIPKIN_HOST
          value: "zipkin-server"         
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8021
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 5
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8021
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 5
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi