apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume
  labels:
    type: local
    app: minio
  namespace: twitter-website
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/minio